---
- hosts: all
  sudo: no
  remote_user: vagrant
  tasks:
    - name: install packages
      yum:
        name=ruby
        state=latest
      with_items:
        - ruby
        - git

    - name: create dotfiles directory
      file:
        path={{ item }}
        state=directory
      with_items:
        - ~/dotfiles
        - ~/.vim/bundle
        - ~/.vim/autoload

    - name: setup dotfiles
      git:
        repo=git@github.com:muramasa64/dotfiles.git
        dest=~/dotfiles
        version=master
        accept_hostkey=yes

    - name: symlink dotfiles
      command:
        ~/dotfiles/dotfileslink.rb

    - name: install vim-neobundle
      git:
        repo=git@github.com:Shougo/neobundle.vim.git
        dest=~/.vim/bundle/neobundle.vim
        version=master
        accept_hostkey=yes

    - name: install vim-vimproc
      git:
        repo=git@github.com:Shougo/vimproc.vim.git
        dest=~/.vim/bundle/vimproc.vim
        version=master
        accept_hostkey=yes

    - name: make vim-vimproc
      command:
        make chdir=~/.vim/bundle/vimproc.vim

    - name: install vim-plug
      get_url:
        url=https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest=~/.vim/autoload/plug.vim
